// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly AdminClass s_Admin = new AdminClass();
    public static AdminClass Admin { get { return s_Admin; } }
    public static Yeast.Controllers.HomeController Home = new Yeast.Controllers.T4MVC_HomeController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdminClass
    {
        public readonly string Name = "Admin";
        public Yeast.Areas.Admin.Controllers.CategoryController Category = new Yeast.Areas.Admin.Controllers.T4MVC_CategoryController();
        public Yeast.Areas.Admin.Controllers.DashboardController Dashboard = new Yeast.Areas.Admin.Controllers.T4MVC_DashboardController();
        public Yeast.Areas.Admin.Controllers.PostController Post = new Yeast.Areas.Admin.Controllers.T4MVC_PostController();
        public Yeast.Areas.Admin.Controllers.ProductController Product = new Yeast.Areas.Admin.Controllers.T4MVC_ProductController();
        public Yeast.Areas.Admin.Controllers.TagController Tag = new Yeast.Areas.Admin.Controllers.T4MVC_TagController();
        public Yeast.Areas.Admin.Controllers.UserController User = new Yeast.Areas.Admin.Controllers.T4MVC_UserController();
        public T4MVC.Admin.SharedController Shared = new T4MVC.Admin.SharedController();
    }
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class css {
            public const string UrlPath = "~/Content/css";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _32px_png = Url("32px.png");
            public static readonly string _40px_png = Url("40px.png");
            public static readonly string bootstrap_rtl_min_css = Url("bootstrap-rtl.min.css");
            public static readonly string bootstrap_switch_rtl_min_css = Url("bootstrap-switch-rtl.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap_table {
                public const string UrlPath = "~/Content/css/bootstrap-table";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string bootstrap_editable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-editable.min.css") ? Url("bootstrap-editable.min.css") : Url("bootstrap-editable.css");
                public static readonly string bootstrap_table_sticky_header_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table-sticky-header.min.css") ? Url("bootstrap-table-sticky-header.min.css") : Url("bootstrap-table-sticky-header.css");
                public static readonly string bootstrap_table_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table.min.css") ? Url("bootstrap-table.min.css") : Url("bootstrap-table.css");
            }
        
            public static readonly string components_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/components-rtl.min.css") ? Url("components-rtl.min.css") : Url("components-rtl.css");
            public static readonly string default_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/default-rtl.min.css") ? Url("default-rtl.min.css") : Url("default-rtl.css");
            public static readonly string enjoyhint_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/enjoyhint.min.css") ? Url("enjoyhint.min.css") : Url("enjoyhint.css");
            public static readonly string filepond_min_css = Url("filepond.min.css");
            public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
            public static readonly string jstree_min_css = Url("jstree.min.css");
            public static readonly string ladda_themeless_rtl_min_css = Url("ladda-themeless-rtl.min.css");
            public static readonly string layout_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/layout-rtl.min.css") ? Url("layout-rtl.min.css") : Url("layout-rtl.css");
            public static readonly string ma5slider_min_css = Url("ma5slider.min.css");
            public static readonly string plugins_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/plugins-rtl.min.css") ? Url("plugins-rtl.min.css") : Url("plugins-rtl.css");
            public static readonly string select2_bootstrap_min_css = Url("select2-bootstrap.min.css");
            public static readonly string select2_min_css = Url("select2.min.css");
            public static readonly string simple_line_icons_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/simple-line-icons.min.css") ? Url("simple-line-icons.min.css") : Url("simple-line-icons.css");
            public static readonly string sweetalert_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sweetalert.min.css") ? Url("sweetalert.min.css") : Url("sweetalert.css");
            public static readonly string Yeast_ltr_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Yeast-ltr.min.css") ? Url("Yeast-ltr.min.css") : Url("Yeast-ltr.css");
            public static readonly string Yeast_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Yeast.min.css") ? Url("Yeast.min.css") : Url("Yeast.css");
            public static readonly string YeastFont_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/YeastFont.min.css") ? Url("YeastFont.min.css") : Url("YeastFont.css");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            public const string UrlPath = "~/Content/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap {
                public const string UrlPath = "~/Content/fonts/bootstrap";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string glyphicons_halflings_regular_eot = Url("glyphicons-halflings-regular.eot");
                public static readonly string glyphicons_halflings_regular_svg = Url("glyphicons-halflings-regular.svg");
                public static readonly string glyphicons_halflings_regular_ttf = Url("glyphicons-halflings-regular.ttf");
                public static readonly string glyphicons_halflings_regular_woff = Url("glyphicons-halflings-regular.woff");
                public static readonly string glyphicons_halflings_regular_woff2 = Url("glyphicons-halflings-regular.woff2");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class eot {
                public const string UrlPath = "~/Content/fonts/eot";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            public static readonly string fontawesome_webfont_eot = Url("fontawesome-webfont.eot");
            public static readonly string fontawesome_webfont_svg = Url("fontawesome-webfont.svg");
            public static readonly string fontawesome_webfont_ttf = Url("fontawesome-webfont.ttf");
            public static readonly string fontawesome_webfont_woff = Url("fontawesome-webfont.woff");
            public static readonly string fontawesome_webfont_woff2 = Url("fontawesome-webfont.woff2");
            public static readonly string FontAwesome_otf = Url("FontAwesome.otf");
            public static readonly string Simple_Line_Icons_dev_svg = Url("Simple-Line-Icons.dev.svg");
            public static readonly string Simple_Line_Icons_eot = Url("Simple-Line-Icons.eot");
            public static readonly string Simple_Line_Icons_svg = Url("Simple-Line-Icons.svg");
            public static readonly string Simple_Line_Icons_ttf = Url("Simple-Line-Icons.ttf");
            public static readonly string Simple_Line_Icons_woff = Url("Simple-Line-Icons.woff");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class svg {
                public const string UrlPath = "~/Content/fonts/svg";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ttf {
                public const string UrlPath = "~/Content/fonts/ttf";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class woff {
                public const string UrlPath = "~/Content/fonts/woff";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class woff2 {
                public const string UrlPath = "~/Content/fonts/woff2";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class froala {
            public const string UrlPath = "~/Content/froala";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                public const string UrlPath = "~/Content/froala/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string froala_editor_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/froala_editor.min.css") ? Url("froala_editor.min.css") : Url("froala_editor.css");
                public static readonly string froala_editor_min_css = Url("froala_editor.min.css");
                public static readonly string froala_editor_pkgd_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/froala_editor.pkgd.min.css") ? Url("froala_editor.pkgd.min.css") : Url("froala_editor.pkgd.css");
                public static readonly string froala_editor_pkgd_min_css = Url("froala_editor.pkgd.min.css");
                public static readonly string froala_style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/froala_style.min.css") ? Url("froala_style.min.css") : Url("froala_style.css");
                public static readonly string froala_style_min_css = Url("froala_style.min.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class plugins {
                    public const string UrlPath = "~/Content/froala/css/plugins";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string char_counter_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/char_counter.min.css") ? Url("char_counter.min.css") : Url("char_counter.css");
                    public static readonly string char_counter_min_css = Url("char_counter.min.css");
                    public static readonly string code_view_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/code_view.min.css") ? Url("code_view.min.css") : Url("code_view.css");
                    public static readonly string code_view_min_css = Url("code_view.min.css");
                    public static readonly string colors_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/colors.min.css") ? Url("colors.min.css") : Url("colors.css");
                    public static readonly string colors_min_css = Url("colors.min.css");
                    public static readonly string draggable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/draggable.min.css") ? Url("draggable.min.css") : Url("draggable.css");
                    public static readonly string draggable_min_css = Url("draggable.min.css");
                    public static readonly string emoticons_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/emoticons.min.css") ? Url("emoticons.min.css") : Url("emoticons.css");
                    public static readonly string emoticons_min_css = Url("emoticons.min.css");
                    public static readonly string file_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/file.min.css") ? Url("file.min.css") : Url("file.css");
                    public static readonly string file_min_css = Url("file.min.css");
                    public static readonly string fullscreen_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fullscreen.min.css") ? Url("fullscreen.min.css") : Url("fullscreen.css");
                    public static readonly string fullscreen_min_css = Url("fullscreen.min.css");
                    public static readonly string help_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/help.min.css") ? Url("help.min.css") : Url("help.css");
                    public static readonly string help_min_css = Url("help.min.css");
                    public static readonly string image_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/image.min.css") ? Url("image.min.css") : Url("image.css");
                    public static readonly string image_min_css = Url("image.min.css");
                    public static readonly string image_manager_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/image_manager.min.css") ? Url("image_manager.min.css") : Url("image_manager.css");
                    public static readonly string image_manager_min_css = Url("image_manager.min.css");
                    public static readonly string line_breaker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/line_breaker.min.css") ? Url("line_breaker.min.css") : Url("line_breaker.css");
                    public static readonly string line_breaker_min_css = Url("line_breaker.min.css");
                    public static readonly string quick_insert_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/quick_insert.min.css") ? Url("quick_insert.min.css") : Url("quick_insert.css");
                    public static readonly string quick_insert_min_css = Url("quick_insert.min.css");
                    public static readonly string special_characters_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/special_characters.min.css") ? Url("special_characters.min.css") : Url("special_characters.css");
                    public static readonly string special_characters_min_css = Url("special_characters.min.css");
                    public static readonly string table_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/table.min.css") ? Url("table.min.css") : Url("table.css");
                    public static readonly string table_min_css = Url("table.min.css");
                    public static readonly string video_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/video.min.css") ? Url("video.min.css") : Url("video.css");
                    public static readonly string video_min_css = Url("video.min.css");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class themes {
                    public const string UrlPath = "~/Content/froala/css/themes";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string dark_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dark.min.css") ? Url("dark.min.css") : Url("dark.css");
                    public static readonly string dark_min_css = Url("dark.min.css");
                    public static readonly string gray_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/gray.min.css") ? Url("gray.min.css") : Url("gray.css");
                    public static readonly string gray_min_css = Url("gray.min.css");
                    public static readonly string red_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/red.min.css") ? Url("red.min.css") : Url("red.css");
                    public static readonly string red_min_css = Url("red.min.css");
                    public static readonly string royal_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/royal.min.css") ? Url("royal.min.css") : Url("royal.css");
                    public static readonly string royal_min_css = Url("royal.min.css");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class third_party {
                    public const string UrlPath = "~/Content/froala/css/third_party";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string embedly_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/embedly.min.css") ? Url("embedly.min.css") : Url("embedly.css");
                    public static readonly string embedly_min_css = Url("embedly.min.css");
                    public static readonly string spell_checker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/spell_checker.min.css") ? Url("spell_checker.min.css") : Url("spell_checker.css");
                    public static readonly string spell_checker_min_css = Url("spell_checker.min.css");
                }
            
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class js {
                public const string UrlPath = "~/Content/froala/js";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string froala_editor_min_js = Url("froala_editor.min.js");
                public static readonly string froala_editor_pkgd_min_js = Url("froala_editor.pkgd.min.js");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class languages {
                    public const string UrlPath = "~/Content/froala/js/languages";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string ar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ar.min.js") ? Url("ar.min.js") : Url("ar.js");
                    public static readonly string bs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bs.min.js") ? Url("bs.min.js") : Url("bs.js");
                    public static readonly string cs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/cs.min.js") ? Url("cs.min.js") : Url("cs.js");
                    public static readonly string da_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/da.min.js") ? Url("da.min.js") : Url("da.js");
                    public static readonly string de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/de.min.js") ? Url("de.min.js") : Url("de.js");
                    public static readonly string en_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/en_ca.min.js") ? Url("en_ca.min.js") : Url("en_ca.js");
                    public static readonly string en_gb_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/en_gb.min.js") ? Url("en_gb.min.js") : Url("en_gb.js");
                    public static readonly string es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/es.min.js") ? Url("es.min.js") : Url("es.js");
                    public static readonly string et_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/et.min.js") ? Url("et.min.js") : Url("et.js");
                    public static readonly string fa_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fa.min.js") ? Url("fa.min.js") : Url("fa.js");
                    public static readonly string fi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fi.min.js") ? Url("fi.min.js") : Url("fi.js");
                    public static readonly string fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fr.min.js") ? Url("fr.min.js") : Url("fr.js");
                    public static readonly string he_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/he.min.js") ? Url("he.min.js") : Url("he.js");
                    public static readonly string hr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/hr.min.js") ? Url("hr.min.js") : Url("hr.js");
                    public static readonly string hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/hu.min.js") ? Url("hu.min.js") : Url("hu.js");
                    public static readonly string id_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/id.min.js") ? Url("id.min.js") : Url("id.js");
                    public static readonly string it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/it.min.js") ? Url("it.min.js") : Url("it.js");
                    public static readonly string ja_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ja.min.js") ? Url("ja.min.js") : Url("ja.js");
                    public static readonly string ko_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ko.min.js") ? Url("ko.min.js") : Url("ko.js");
                    public static readonly string me_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/me.min.js") ? Url("me.min.js") : Url("me.js");
                    public static readonly string nb_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/nb.min.js") ? Url("nb.min.js") : Url("nb.js");
                    public static readonly string nl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/nl.min.js") ? Url("nl.min.js") : Url("nl.js");
                    public static readonly string pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/pl.min.js") ? Url("pl.min.js") : Url("pl.js");
                    public static readonly string pt_br_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/pt_br.min.js") ? Url("pt_br.min.js") : Url("pt_br.js");
                    public static readonly string pt_pt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/pt_pt.min.js") ? Url("pt_pt.min.js") : Url("pt_pt.js");
                    public static readonly string ro_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ro.min.js") ? Url("ro.min.js") : Url("ro.js");
                    public static readonly string ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ru.min.js") ? Url("ru.min.js") : Url("ru.js");
                    public static readonly string sk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sk.min.js") ? Url("sk.min.js") : Url("sk.js");
                    public static readonly string sr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sr.min.js") ? Url("sr.min.js") : Url("sr.js");
                    public static readonly string sv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sv.min.js") ? Url("sv.min.js") : Url("sv.js");
                    public static readonly string th_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/th.min.js") ? Url("th.min.js") : Url("th.js");
                    public static readonly string tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tr.min.js") ? Url("tr.min.js") : Url("tr.js");
                    public static readonly string uk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/uk.min.js") ? Url("uk.min.js") : Url("uk.js");
                    public static readonly string vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/vi.min.js") ? Url("vi.min.js") : Url("vi.js");
                    public static readonly string zh_cn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/zh_cn.min.js") ? Url("zh_cn.min.js") : Url("zh_cn.js");
                    public static readonly string zh_tw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/zh_tw.min.js") ? Url("zh_tw.min.js") : Url("zh_tw.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class plugins {
                    public const string UrlPath = "~/Content/froala/js/plugins";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string align_min_js = Url("align.min.js");
                    public static readonly string char_counter_min_js = Url("char_counter.min.js");
                    public static readonly string code_beautifier_min_js = Url("code_beautifier.min.js");
                    public static readonly string code_view_min_js = Url("code_view.min.js");
                    public static readonly string colors_min_js = Url("colors.min.js");
                    public static readonly string draggable_min_js = Url("draggable.min.js");
                    public static readonly string emoticons_min_js = Url("emoticons.min.js");
                    public static readonly string entities_min_js = Url("entities.min.js");
                    public static readonly string file_min_js = Url("file.min.js");
                    public static readonly string font_family_min_js = Url("font_family.min.js");
                    public static readonly string font_size_min_js = Url("font_size.min.js");
                    public static readonly string forms_min_js = Url("forms.min.js");
                    public static readonly string fullscreen_min_js = Url("fullscreen.min.js");
                    public static readonly string help_min_js = Url("help.min.js");
                    public static readonly string image_min_js = Url("image.min.js");
                    public static readonly string image_manager_min_js = Url("image_manager.min.js");
                    public static readonly string inline_style_min_js = Url("inline_style.min.js");
                    public static readonly string line_breaker_min_js = Url("line_breaker.min.js");
                    public static readonly string link_min_js = Url("link.min.js");
                    public static readonly string lists_min_js = Url("lists.min.js");
                    public static readonly string paragraph_format_min_js = Url("paragraph_format.min.js");
                    public static readonly string paragraph_style_min_js = Url("paragraph_style.min.js");
                    public static readonly string print_min_js = Url("print.min.js");
                    public static readonly string quick_insert_min_js = Url("quick_insert.min.js");
                    public static readonly string quote_min_js = Url("quote.min.js");
                    public static readonly string save_min_js = Url("save.min.js");
                    public static readonly string special_characters_min_js = Url("special_characters.min.js");
                    public static readonly string table_min_js = Url("table.min.js");
                    public static readonly string url_min_js = Url("url.min.js");
                    public static readonly string video_min_js = Url("video.min.js");
                    public static readonly string word_paste_min_js = Url("word_paste.min.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class third_party {
                    public const string UrlPath = "~/Content/froala/js/third_party";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string embedly_min_js = Url("embedly.min.js");
                    public static readonly string image_aviary_min_js = Url("image_aviary.min.js");
                    public static readonly string spell_checker_min_js = Url("spell_checker.min.js");
                }
            
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            public const string UrlPath = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _100_thickbox_default_min__11089_1499311175_jpg = Url("100-thickbox_default-min__11089.1499311175.jpg");
            public static readonly string _104_thickbox_default_min__37458_1499308829_jpg = Url("104-thickbox_default-min__37458.1499308829.jpg");
            public static readonly string _104_thickbox_default_min__94774_1499311192_jpg = Url("104-thickbox_default-min__94774.1499311192.jpg");
            public static readonly string _132_thickbox_default_min__15237_1499306777_jpg = Url("132-thickbox_default-min__15237.1499306777.jpg");
            public static readonly string _58_thickbox_default_min__02732_1499309302_jpg = Url("58-thickbox_default-min__02732.1499309302.jpg");
            public static readonly string _59_thickbox_default_min__78909_1499309309_jpg = Url("59-thickbox_default-min__78909.1499309309.jpg");
            public static readonly string _85_thickbox_default_min__01047_1_jpg = Url("85-thickbox_default-min__01047.1.jpg");
            public static readonly string _85_thickbox_default_min__01047_1499309682_jpg = Url("85-thickbox_default-min__01047.1499309682.jpg");
            public static readonly string _86_thickbox_default_min__39805_1499309776_jpg = Url("86-thickbox_default-min__39805.1499309776.jpg");
            public static readonly string _88_thickbox_default_min_rs__76988_1499309560_jpg = Url("88-thickbox_default-min-rs__76988.1499309560.jpg");
            public static readonly string _89_thickbox_default_1_min__08955_1499250554_jpg = Url("89-thickbox_default_1-min__08955.1499250554.jpg");
            public static readonly string _90_thickbox_default_min__24015_1499250559_jpg = Url("90-thickbox_default-min__24015.1499250559.jpg");
            public static readonly string _93_thickbox_default_min__61912_1499246850_jpg = Url("93-thickbox_default-min__61912.1499246850.jpg");
            public static readonly string _94_thickbox_default_min__52854_1499246844_jpg = Url("94-thickbox_default-min__52854.1499246844.jpg");
            public static readonly string bg_breadcrumb_min_jpg = Url("bg-breadcrumb-min.jpg");
            public static readonly string bg_image_min_jpg = Url("bg-image-min.jpg");
            public static readonly string img_about_min_jpg = Url("img-about-min.jpg");
            public static readonly string img_cate_2_min_jpg = Url("img-cate-2-min.jpg");
            public static readonly string img_cate_3_min_jpg = Url("img-cate-3-min.jpg");
            public static readonly string img_cate_min_jpg = Url("img-cate-min.jpg");
            public static readonly string imgpsh_fullsize_rs_jpg = Url("imgpsh-fullsize-rs.jpg");
            public static readonly string logo_min_1506501989__87899_original_png = Url("logo-min_1506501989__87899.original.png");
            public static readonly string newletter_bg_png = Url("newletter-bg.png");
            public static readonly string pnewletter_bg_png = Url("pnewletter-bg.png");
            public static readonly string remove_icon_small_png = Url("remove-icon-small.png");
            public static readonly string s1_min__94940_1499310560_jpg = Url("s1-min__94940.1499310560.jpg");
            public static readonly string s10_min_rs__09132_1499310114_jpg = Url("s10-min-rs__09132.1499310114.jpg");
            public static readonly string s11_min__88583_1499310568_jpg = Url("s11-min__88583.1499310568.jpg");
            public static readonly string s5_min__84178_1499310668_jpg = Url("s5-min__84178.1499310668.jpg");
            public static readonly string s6_min__43240_1499310437_jpg = Url("s6-min__43240.1499310437.jpg");
            public static readonly string s9_min_rs__06198_1499309930_jpg = Url("s9-min-rs__06198.1499309930.jpg");
            public static readonly string searchicon_png = Url("searchicon.png");
            public static readonly string slideshow_image_1_min_rs_jpg = Url("slideshow_image_1-min-rs.jpg");
            public static readonly string slideshow_image_2_min_jpg = Url("slideshow_image_2-min.jpg");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class js {
            public const string UrlPath = "~/Content/js";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string app_min_js = Url("app.min.js");
            public static readonly string bootstrap_switch_min_js = Url("bootstrap-switch.min.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap_table {
                public const string UrlPath = "~/Content/js/bootstrap-table";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string bootstrap_table_cookie_min_js = Url("bootstrap-table-cookie.min.js");
                public static readonly string bootstrap_table_export_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table-export.min.js") ? Url("bootstrap-table-export.min.js") : Url("bootstrap-table-export.js");
                public static readonly string bootstrap_table_mobile_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table-mobile.min.js") ? Url("bootstrap-table-mobile.min.js") : Url("bootstrap-table-mobile.js");
                public static readonly string bootstrap_table_select2_filter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table-select2-filter.min.js") ? Url("bootstrap-table-select2-filter.min.js") : Url("bootstrap-table-select2-filter.js");
                public static readonly string bootstrap_table_sticky_header_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table-sticky-header.min.js") ? Url("bootstrap-table-sticky-header.min.js") : Url("bootstrap-table-sticky-header.js");
                public static readonly string bootstrap_table_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table.min.js") ? Url("bootstrap-table.min.js") : Url("bootstrap-table.js");
                public static readonly string tableExport_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tableExport.min.js") ? Url("tableExport.min.js") : Url("tableExport.js");
            }
        
            public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
            public static readonly string enjoyhint_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/enjoyhint.min.js") ? Url("enjoyhint.min.js") : Url("enjoyhint.js");
            public static readonly string filepond_esm_min_js = Url("filepond.esm.min.js");
            public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
            public static readonly string jquery_3_3_1_min_js = Url("jquery-3.3.1.min.js");
            public static readonly string jquery_ui_min_js = Url("jquery-ui.min.js");
            public static readonly string jquery_blockui_min_js = Url("jquery.blockui.min.js");
            public static readonly string jquery_min_js = Url("jquery.min.js");
            public static readonly string jquery_slimscroll_min_js = Url("jquery.slimscroll.min.js");
            public static readonly string jquery_ui_touch_punch_min_js = Url("jquery.ui.touch-punch.min.js");
            public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
            public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
            public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
            public static readonly string js_cookie_min_js = Url("js.cookie.min.js");
            public static readonly string jstree_min_js = Url("jstree.min.js");
            public static readonly string ladda_min_js = Url("ladda.min.js");
            public static readonly string layout_min_js = Url("layout.min.js");
            public static readonly string ma5slider_min_js = Url("ma5slider.min.js");
            public static readonly string persianumber_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/persianumber.min.js") ? Url("persianumber.min.js") : Url("persianumber.js");
            public static readonly string quick_nav_min_js = Url("quick-nav.min.js");
            public static readonly string select2_min_js = Url("select2.min.js");
            public static readonly string spin_min_js = Url("spin.min.js");
            public static readonly string sweetalert_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sweetalert.min.js") ? Url("sweetalert.min.js") : Url("sweetalert.js");
            public static readonly string theme_bundle_chunk_16_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/theme-bundle.chunk.16.min.js") ? Url("theme-bundle.chunk.16.min.js") : Url("theme-bundle.chunk.16.js");
            public static readonly string Yeast_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Yeast.min.js") ? Url("Yeast.min.js") : Url("Yeast.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class upload {
            public const string UrlPath = "~/Content/upload";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class files {
                public const string UrlPath = "~/Content/upload/files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class images {
                public const string UrlPath = "~/Content/upload/images";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class videos {
                public const string UrlPath = "~/Content/upload/videos";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Content 
        {
            public static partial class css 
            {
                public static partial class bootstrap_table 
                {
                    public static class Assets
                    {
                        public static readonly string bootstrap_editable_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-table/bootstrap-editable.css");
                        public static readonly string bootstrap_table_sticky_header_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-table/bootstrap-table-sticky-header.css");
                        public static readonly string bootstrap_table_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-table/bootstrap-table.css");
                    }
                }
                public static class Assets
                {
                    public static readonly string bootstrap_rtl_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-rtl.min.css");
                    public static readonly string bootstrap_switch_rtl_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-switch-rtl.min.css");
                    public static readonly string components_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/components-rtl.css");
                    public static readonly string default_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/default-rtl.css");
                    public static readonly string enjoyhint_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/enjoyhint.css");
                    public static readonly string filepond_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/filepond.min.css");
                    public static readonly string font_awesome_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/font-awesome.min.css");
                    public static readonly string jstree_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/jstree.min.css");
                    public static readonly string ladda_themeless_rtl_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/ladda-themeless-rtl.min.css");
                    public static readonly string layout_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/layout-rtl.css");
                    public static readonly string ma5slider_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/ma5slider.min.css");
                    public static readonly string plugins_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/plugins-rtl.css");
                    public static readonly string select2_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/select2-bootstrap.min.css");
                    public static readonly string select2_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/select2.min.css");
                    public static readonly string simple_line_icons_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/simple-line-icons.css");
                    public static readonly string sweetalert_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/sweetalert.css");
                    public static readonly string Yeast_ltr_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/Yeast-ltr.css");
                    public static readonly string Yeast_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/Yeast.css");
                    public static readonly string YeastFont_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/YeastFont.css");
                }
            }
            public static partial class fonts 
            {
                public static partial class bootstrap 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class eot 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class svg 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class ttf 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class woff 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class woff2 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class froala 
            {
                public static partial class css 
                {
                    public static partial class plugins 
                    {
                        public static class Assets
                        {
                            public static readonly string char_counter_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/char_counter.css");
                            public static readonly string char_counter_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/char_counter.min.css");
                            public static readonly string code_view_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/code_view.css");
                            public static readonly string code_view_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/code_view.min.css");
                            public static readonly string colors_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/colors.css");
                            public static readonly string colors_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/colors.min.css");
                            public static readonly string draggable_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/draggable.css");
                            public static readonly string draggable_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/draggable.min.css");
                            public static readonly string emoticons_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/emoticons.css");
                            public static readonly string emoticons_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/emoticons.min.css");
                            public static readonly string file_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/file.css");
                            public static readonly string file_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/file.min.css");
                            public static readonly string fullscreen_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/fullscreen.css");
                            public static readonly string fullscreen_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/fullscreen.min.css");
                            public static readonly string help_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/help.css");
                            public static readonly string help_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/help.min.css");
                            public static readonly string image_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/image.css");
                            public static readonly string image_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/image.min.css");
                            public static readonly string image_manager_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/image_manager.css");
                            public static readonly string image_manager_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/image_manager.min.css");
                            public static readonly string line_breaker_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/line_breaker.css");
                            public static readonly string line_breaker_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/line_breaker.min.css");
                            public static readonly string quick_insert_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/quick_insert.css");
                            public static readonly string quick_insert_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/quick_insert.min.css");
                            public static readonly string special_characters_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/special_characters.css");
                            public static readonly string special_characters_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/special_characters.min.css");
                            public static readonly string table_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/table.css");
                            public static readonly string table_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/table.min.css");
                            public static readonly string video_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/video.css");
                            public static readonly string video_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/plugins/video.min.css");
                        }
                    }
                    public static partial class themes 
                    {
                        public static class Assets
                        {
                            public static readonly string dark_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/dark.css");
                            public static readonly string dark_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/dark.min.css");
                            public static readonly string gray_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/gray.css");
                            public static readonly string gray_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/gray.min.css");
                            public static readonly string red_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/red.css");
                            public static readonly string red_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/red.min.css");
                            public static readonly string royal_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/royal.css");
                            public static readonly string royal_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/themes/royal.min.css");
                        }
                    }
                    public static partial class third_party 
                    {
                        public static class Assets
                        {
                            public static readonly string embedly_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/third_party/embedly.css");
                            public static readonly string embedly_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/third_party/embedly.min.css");
                            public static readonly string spell_checker_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/third_party/spell_checker.css");
                            public static readonly string spell_checker_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/third_party/spell_checker.min.css");
                        }
                    }
                    public static class Assets
                    {
                        public static readonly string froala_editor_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/froala_editor.css");
                        public static readonly string froala_editor_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/froala_editor.min.css");
                        public static readonly string froala_editor_pkgd_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/froala_editor.pkgd.css");
                        public static readonly string froala_editor_pkgd_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/froala_editor.pkgd.min.css");
                        public static readonly string froala_style_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/froala_style.css");
                        public static readonly string froala_style_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/froala/css/froala_style.min.css");
                    }
                }
                public static partial class js 
                {
                    public static partial class languages 
                    {
                        public static class Assets
                        {
                            public static readonly string ar_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/ar.js"); 
                            public static readonly string bs_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/bs.js"); 
                            public static readonly string cs_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/cs.js"); 
                            public static readonly string da_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/da.js"); 
                            public static readonly string de_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/de.js"); 
                            public static readonly string en_ca_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/en_ca.js"); 
                            public static readonly string en_gb_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/en_gb.js"); 
                            public static readonly string es_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/es.js"); 
                            public static readonly string et_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/et.js"); 
                            public static readonly string fa_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/fa.js"); 
                            public static readonly string fi_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/fi.js"); 
                            public static readonly string fr_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/fr.js"); 
                            public static readonly string he_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/he.js"); 
                            public static readonly string hr_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/hr.js"); 
                            public static readonly string hu_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/hu.js"); 
                            public static readonly string id_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/id.js"); 
                            public static readonly string it_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/it.js"); 
                            public static readonly string ja_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/ja.js"); 
                            public static readonly string ko_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/ko.js"); 
                            public static readonly string me_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/me.js"); 
                            public static readonly string nb_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/nb.js"); 
                            public static readonly string nl_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/nl.js"); 
                            public static readonly string pl_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/pl.js"); 
                            public static readonly string pt_br_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/pt_br.js"); 
                            public static readonly string pt_pt_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/pt_pt.js"); 
                            public static readonly string ro_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/ro.js"); 
                            public static readonly string ru_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/ru.js"); 
                            public static readonly string sk_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/sk.js"); 
                            public static readonly string sr_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/sr.js"); 
                            public static readonly string sv_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/sv.js"); 
                            public static readonly string th_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/th.js"); 
                            public static readonly string tr_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/tr.js"); 
                            public static readonly string uk_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/uk.js"); 
                            public static readonly string vi_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/vi.js"); 
                            public static readonly string zh_cn_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/zh_cn.js"); 
                            public static readonly string zh_tw_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/languages/zh_tw.js"); 
                        }
                    }
                    public static partial class plugins 
                    {
                        public static class Assets
                        {
                            public static readonly string align_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/align.min.js"); 
                            public static readonly string char_counter_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/char_counter.min.js"); 
                            public static readonly string code_beautifier_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/code_beautifier.min.js"); 
                            public static readonly string code_view_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/code_view.min.js"); 
                            public static readonly string colors_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/colors.min.js"); 
                            public static readonly string draggable_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/draggable.min.js"); 
                            public static readonly string emoticons_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/emoticons.min.js"); 
                            public static readonly string entities_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/entities.min.js"); 
                            public static readonly string file_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/file.min.js"); 
                            public static readonly string font_family_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/font_family.min.js"); 
                            public static readonly string font_size_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/font_size.min.js"); 
                            public static readonly string forms_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/forms.min.js"); 
                            public static readonly string fullscreen_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/fullscreen.min.js"); 
                            public static readonly string help_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/help.min.js"); 
                            public static readonly string image_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/image.min.js"); 
                            public static readonly string image_manager_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/image_manager.min.js"); 
                            public static readonly string inline_style_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/inline_style.min.js"); 
                            public static readonly string line_breaker_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/line_breaker.min.js"); 
                            public static readonly string link_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/link.min.js"); 
                            public static readonly string lists_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/lists.min.js"); 
                            public static readonly string paragraph_format_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/paragraph_format.min.js"); 
                            public static readonly string paragraph_style_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/paragraph_style.min.js"); 
                            public static readonly string print_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/print.min.js"); 
                            public static readonly string quick_insert_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/quick_insert.min.js"); 
                            public static readonly string quote_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/quote.min.js"); 
                            public static readonly string save_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/save.min.js"); 
                            public static readonly string special_characters_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/special_characters.min.js"); 
                            public static readonly string table_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/table.min.js"); 
                            public static readonly string url_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/url.min.js"); 
                            public static readonly string video_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/video.min.js"); 
                            public static readonly string word_paste_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/plugins/word_paste.min.js"); 
                        }
                    }
                    public static partial class third_party 
                    {
                        public static class Assets
                        {
                            public static readonly string embedly_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/third_party/embedly.min.js"); 
                            public static readonly string image_aviary_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/third_party/image_aviary.min.js"); 
                            public static readonly string spell_checker_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/third_party/spell_checker.min.js"); 
                        }
                    }
                    public static class Assets
                    {
                        public static readonly string froala_editor_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/froala_editor.min.js"); 
                        public static readonly string froala_editor_pkgd_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/froala/js/froala_editor.pkgd.min.js"); 
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static partial class js 
            {
                public static partial class bootstrap_table 
                {
                    public static class Assets
                    {
                        public static readonly string bootstrap_table_cookie_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-cookie.min.js"); 
                        public static readonly string bootstrap_table_export_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-export.js"); 
                        public static readonly string bootstrap_table_mobile_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-mobile.js"); 
                        public static readonly string bootstrap_table_select2_filter_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-select2-filter.js"); 
                        public static readonly string bootstrap_table_sticky_header_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-sticky-header.js"); 
                        public static readonly string bootstrap_table_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table.js"); 
                        public static readonly string tableExport_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/tableExport.js"); 
                    }
                }
                public static class Assets
                {
                    public static readonly string app_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/app.min.js"); 
                    public static readonly string bootstrap_switch_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-switch.min.js"); 
                    public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap.min.js"); 
                    public static readonly string enjoyhint_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/enjoyhint.js"); 
                    public static readonly string filepond_esm_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/filepond.esm.min.js"); 
                    public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery-1.10.2.intellisense.js"); 
                    public static readonly string jquery_3_3_1_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery-3.3.1.min.js"); 
                    public static readonly string jquery_ui_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery-ui.min.js"); 
                    public static readonly string jquery_blockui_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.blockui.min.js"); 
                    public static readonly string jquery_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.min.js"); 
                    public static readonly string jquery_slimscroll_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.slimscroll.min.js"); 
                    public static readonly string jquery_ui_touch_punch_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.ui.touch-punch.min.js"); 
                    public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.validate.js"); 
                    public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.validate.unobtrusive.js"); 
                    public static readonly string js_cookie_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/js.cookie.min.js"); 
                    public static readonly string jstree_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jstree.min.js"); 
                    public static readonly string ladda_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/ladda.min.js"); 
                    public static readonly string layout_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/layout.min.js"); 
                    public static readonly string ma5slider_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/ma5slider.min.js"); 
                    public static readonly string persianumber_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/persianumber.js"); 
                    public static readonly string quick_nav_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/quick-nav.min.js"); 
                    public static readonly string select2_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/select2.min.js"); 
                    public static readonly string spin_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/spin.min.js"); 
                    public static readonly string sweetalert_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/sweetalert.js"); 
                    public static readonly string theme_bundle_chunk_16_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/theme-bundle.chunk.16.js"); 
                    public static readonly string Yeast_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/Yeast.js"); 
                }
            }
            public static partial class upload 
            {
                public static partial class files 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class images 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class videos 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


