// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly AdminClass s_Admin = new AdminClass();
    public static AdminClass Admin { get { return s_Admin; } }
    public static Yeast.Controllers.HomeController Home = new Yeast.Controllers.T4MVC_HomeController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdminClass
    {
        public readonly string Name = "Admin";
        public Yeast.Areas.Admin.Controllers.DashboardController Dashboard = new Yeast.Areas.Admin.Controllers.T4MVC_DashboardController();
        public Yeast.Areas.Admin.Controllers.PostController Post = new Yeast.Areas.Admin.Controllers.T4MVC_PostController();
        public Yeast.Areas.Admin.Controllers.ProductController Product = new Yeast.Areas.Admin.Controllers.T4MVC_ProductController();
        public Yeast.Areas.Admin.Controllers.TagController Tag = new Yeast.Areas.Admin.Controllers.T4MVC_TagController();
        public T4MVC.Admin.SharedController Shared = new T4MVC.Admin.SharedController();
    }
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string jquery_signalR_2_2_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.signalR-2.2.2.min.js") ? Url("jquery.signalR-2.2.2.min.js") : Url("jquery.signalR-2.2.2.js");
        public static readonly string jquery_signalR_2_2_2_min_js = Url("jquery.signalR-2.2.2.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class css {
            public const string UrlPath = "~/Content/css";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_rtl_min_css = Url("bootstrap-rtl.min.css");
            public static readonly string bootstrap_switch_rtl_min_css = Url("bootstrap-switch-rtl.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap_table {
                public const string UrlPath = "~/Content/css/bootstrap-table";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string bootstrap_editable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-editable.min.css") ? Url("bootstrap-editable.min.css") : Url("bootstrap-editable.css");
                public static readonly string bootstrap_table_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table.min.css") ? Url("bootstrap-table.min.css") : Url("bootstrap-table.css");
            }
        
            public static readonly string components_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/components-rtl.min.css") ? Url("components-rtl.min.css") : Url("components-rtl.css");
            public static readonly string default_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/default-rtl.min.css") ? Url("default-rtl.min.css") : Url("default-rtl.css");
            public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
            public static readonly string ladda_themeless_rtl_min_css = Url("ladda-themeless-rtl.min.css");
            public static readonly string layout_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/layout-rtl.min.css") ? Url("layout-rtl.min.css") : Url("layout-rtl.css");
            public static readonly string plugins_rtl_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/plugins-rtl.min.css") ? Url("plugins-rtl.min.css") : Url("plugins-rtl.css");
            public static readonly string simple_line_icons_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/simple-line-icons.min.css") ? Url("simple-line-icons.min.css") : Url("simple-line-icons.css");
            public static readonly string sweetalert_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sweetalert.min.css") ? Url("sweetalert.min.css") : Url("sweetalert.css");
            public static readonly string Yeast_ltr_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Yeast-ltr.min.css") ? Url("Yeast-ltr.min.css") : Url("Yeast-ltr.css");
            public static readonly string Yeast_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Yeast.min.css") ? Url("Yeast.min.css") : Url("Yeast.css");
            public static readonly string YeastFont_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/YeastFont.min.css") ? Url("YeastFont.min.css") : Url("YeastFont.css");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            public const string UrlPath = "~/Content/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class eot {
                public const string UrlPath = "~/Content/fonts/eot";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            public static readonly string fontawesome_webfont_eot = Url("fontawesome-webfont.eot");
            public static readonly string fontawesome_webfont_svg = Url("fontawesome-webfont.svg");
            public static readonly string fontawesome_webfont_ttf = Url("fontawesome-webfont.ttf");
            public static readonly string fontawesome_webfont_woff = Url("fontawesome-webfont.woff");
            public static readonly string fontawesome_webfont_woff2 = Url("fontawesome-webfont.woff2");
            public static readonly string FontAwesome_otf = Url("FontAwesome.otf");
            public static readonly string Simple_Line_Icons_dev_svg = Url("Simple-Line-Icons.dev.svg");
            public static readonly string Simple_Line_Icons_eot = Url("Simple-Line-Icons.eot");
            public static readonly string Simple_Line_Icons_svg = Url("Simple-Line-Icons.svg");
            public static readonly string Simple_Line_Icons_ttf = Url("Simple-Line-Icons.ttf");
            public static readonly string Simple_Line_Icons_woff = Url("Simple-Line-Icons.woff");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class svg {
                public const string UrlPath = "~/Content/fonts/svg";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ttf {
                public const string UrlPath = "~/Content/fonts/ttf";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class woff {
                public const string UrlPath = "~/Content/fonts/woff";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class woff2 {
                public const string UrlPath = "~/Content/fonts/woff2";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            public const string UrlPath = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _100_thickbox_default_min__11089_1499311175_jpg = Url("100-thickbox_default-min__11089.1499311175.jpg");
            public static readonly string _104_thickbox_default_min__37458_1499308829_jpg = Url("104-thickbox_default-min__37458.1499308829.jpg");
            public static readonly string _104_thickbox_default_min__94774_1499311192_jpg = Url("104-thickbox_default-min__94774.1499311192.jpg");
            public static readonly string _132_thickbox_default_min__15237_1499306777_jpg = Url("132-thickbox_default-min__15237.1499306777.jpg");
            public static readonly string _58_thickbox_default_min__02732_1499309302_jpg = Url("58-thickbox_default-min__02732.1499309302.jpg");
            public static readonly string _59_thickbox_default_min__78909_1499309309_jpg = Url("59-thickbox_default-min__78909.1499309309.jpg");
            public static readonly string _85_thickbox_default_min__01047_1_jpg = Url("85-thickbox_default-min__01047.1.jpg");
            public static readonly string _85_thickbox_default_min__01047_1499309682_jpg = Url("85-thickbox_default-min__01047.1499309682.jpg");
            public static readonly string _86_thickbox_default_min__39805_1499309776_jpg = Url("86-thickbox_default-min__39805.1499309776.jpg");
            public static readonly string _88_thickbox_default_min_rs__76988_1499309560_jpg = Url("88-thickbox_default-min-rs__76988.1499309560.jpg");
            public static readonly string _89_thickbox_default_1_min__08955_1499250554_jpg = Url("89-thickbox_default_1-min__08955.1499250554.jpg");
            public static readonly string _90_thickbox_default_min__24015_1499250559_jpg = Url("90-thickbox_default-min__24015.1499250559.jpg");
            public static readonly string _93_thickbox_default_min__61912_1499246850_jpg = Url("93-thickbox_default-min__61912.1499246850.jpg");
            public static readonly string _94_thickbox_default_min__52854_1499246844_jpg = Url("94-thickbox_default-min__52854.1499246844.jpg");
            public static readonly string bg_breadcrumb_min_jpg = Url("bg-breadcrumb-min.jpg");
            public static readonly string bg_image_min_jpg = Url("bg-image-min.jpg");
            public static readonly string img_about_min_jpg = Url("img-about-min.jpg");
            public static readonly string img_cate_2_min_jpg = Url("img-cate-2-min.jpg");
            public static readonly string img_cate_3_min_jpg = Url("img-cate-3-min.jpg");
            public static readonly string img_cate_min_jpg = Url("img-cate-min.jpg");
            public static readonly string imgpsh_fullsize_rs_jpg = Url("imgpsh-fullsize-rs.jpg");
            public static readonly string logo_min_1506501989__87899_original_png = Url("logo-min_1506501989__87899.original.png");
            public static readonly string newletter_bg_png = Url("newletter-bg.png");
            public static readonly string s1_min__94940_1499310560_jpg = Url("s1-min__94940.1499310560.jpg");
            public static readonly string s10_min_rs__09132_1499310114_jpg = Url("s10-min-rs__09132.1499310114.jpg");
            public static readonly string s11_min__88583_1499310568_jpg = Url("s11-min__88583.1499310568.jpg");
            public static readonly string s5_min__84178_1499310668_jpg = Url("s5-min__84178.1499310668.jpg");
            public static readonly string s6_min__43240_1499310437_jpg = Url("s6-min__43240.1499310437.jpg");
            public static readonly string s9_min_rs__06198_1499309930_jpg = Url("s9-min-rs__06198.1499309930.jpg");
            public static readonly string slideshow_image_1_min_rs_jpg = Url("slideshow_image_1-min-rs.jpg");
            public static readonly string slideshow_image_2_min_jpg = Url("slideshow_image_2-min.jpg");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class js {
            public const string UrlPath = "~/Content/js";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string app_min_js = Url("app.min.js");
            public static readonly string bootstrap_switch_min_js = Url("bootstrap-switch.min.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap_table {
                public const string UrlPath = "~/Content/js/bootstrap-table";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string bootstrap_table_cookie_min_js = Url("bootstrap-table-cookie.min.js");
                public static readonly string bootstrap_table_select2_filter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table-select2-filter.min.js") ? Url("bootstrap-table-select2-filter.min.js") : Url("bootstrap-table-select2-filter.js");
                public static readonly string bootstrap_table_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-table.min.js") ? Url("bootstrap-table.min.js") : Url("bootstrap-table.js");
            }
        
            public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
            public static readonly string jquery_3_3_1_min_js = Url("jquery-3.3.1.min.js");
            public static readonly string jquery_blockui_min_js = Url("jquery.blockui.min.js");
            public static readonly string jquery_min_js = Url("jquery.min.js");
            public static readonly string jquery_slimscroll_min_js = Url("jquery.slimscroll.min.js");
            public static readonly string js_cookie_min_js = Url("js.cookie.min.js");
            public static readonly string ladda_min_js = Url("ladda.min.js");
            public static readonly string layout_min_js = Url("layout.min.js");
            public static readonly string quick_nav_min_js = Url("quick-nav.min.js");
            public static readonly string spin_min_js = Url("spin.min.js");
            public static readonly string sweetalert_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sweetalert.min.js") ? Url("sweetalert.min.js") : Url("sweetalert.js");
            public static readonly string theme_bundle_chunk_16_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/theme-bundle.chunk.16.min.js") ? Url("theme-bundle.chunk.16.min.js") : Url("theme-bundle.chunk.16.js");
            public static readonly string Yeast_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Yeast.min.js") ? Url("Yeast.min.js") : Url("Yeast.js");
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public static readonly string jquery_signalR_2_2_2_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.signalR-2.2.2.js"); 
                public static readonly string jquery_signalR_2_2_2_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.signalR-2.2.2.min.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class css 
            {
                public static partial class bootstrap_table 
                {
                    public static class Assets
                    {
                        public static readonly string bootstrap_editable_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-table/bootstrap-editable.css");
                        public static readonly string bootstrap_table_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-table/bootstrap-table.css");
                    }
                }
                public static class Assets
                {
                    public static readonly string bootstrap_rtl_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-rtl.min.css");
                    public static readonly string bootstrap_switch_rtl_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap-switch-rtl.min.css");
                    public static readonly string components_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/components-rtl.css");
                    public static readonly string default_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/default-rtl.css");
                    public static readonly string font_awesome_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/font-awesome.min.css");
                    public static readonly string ladda_themeless_rtl_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/ladda-themeless-rtl.min.css");
                    public static readonly string layout_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/layout-rtl.css");
                    public static readonly string plugins_rtl_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/plugins-rtl.css");
                    public static readonly string simple_line_icons_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/simple-line-icons.css");
                    public static readonly string sweetalert_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/sweetalert.css");
                    public static readonly string Yeast_ltr_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/Yeast-ltr.css");
                    public static readonly string Yeast_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/Yeast.css");
                    public static readonly string YeastFont_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/YeastFont.css");
                }
            }
            public static partial class fonts 
            {
                public static partial class eot 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class svg 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class ttf 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class woff 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class woff2 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static partial class js 
            {
                public static partial class bootstrap_table 
                {
                    public static class Assets
                    {
                        public static readonly string bootstrap_table_cookie_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-cookie.min.js"); 
                        public static readonly string bootstrap_table_select2_filter_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table-select2-filter.js"); 
                        public static readonly string bootstrap_table_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-table/bootstrap-table.js"); 
                    }
                }
                public static class Assets
                {
                    public static readonly string app_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/app.min.js"); 
                    public static readonly string bootstrap_switch_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap-switch.min.js"); 
                    public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap.min.js"); 
                    public static readonly string jquery_3_3_1_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery-3.3.1.min.js"); 
                    public static readonly string jquery_blockui_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.blockui.min.js"); 
                    public static readonly string jquery_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.min.js"); 
                    public static readonly string jquery_slimscroll_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.slimscroll.min.js"); 
                    public static readonly string js_cookie_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/js.cookie.min.js"); 
                    public static readonly string ladda_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/ladda.min.js"); 
                    public static readonly string layout_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/layout.min.js"); 
                    public static readonly string quick_nav_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/quick-nav.min.js"); 
                    public static readonly string spin_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/spin.min.js"); 
                    public static readonly string sweetalert_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/sweetalert.js"); 
                    public static readonly string theme_bundle_chunk_16_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/theme-bundle.chunk.16.js"); 
                    public static readonly string Yeast_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/Yeast.js"); 
                }
            }
            public static class Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


